#!/bin/sh
#
#   QTBOOTH Application
#

# Script variables
PROG=qtbooth
PID=/var/run/qtbooth.pid
RETURN_VAL=0

start()
{
    echo "Starting $PROG: "
    start-stop-daemon \
    --start \
    --pidfile $PID \
    -b --exec /usr/bin/qtbooth
    return $?
}

stop()
{
    echo "[`date -u '+%Y-%m-%d %T %Z'`] (sys) Stopping"
    start-stop-daemon --stop --quiet --pidfile $PID
    return $?
}

status() {
        if [ -s $PID ]; then
                echo "$PROG is running as pid `cat $PID`:"
        else
                echo "$PROG is not running."
        fi
}

restart()
{
    stop
    start
    return $?
}

case "$1" in
 start)
       start
    ;;
 stop)
       stop
    ;;
 status)
       status
    ;;
 restart|reload)
       restart
    ;;
 *)
    /bin/echo "Usage: $0 {start|stop|status|restart|reload}"
    RETURN_VAL=1
esac

exit $RETURN_VAL

